#!/bin/sh

if [ "$#" -lt 2 ]
then
    echo "usage: $0 EXENAME TESTDIR [DIFFOPTS ...]"
    exit 1
fi

exe="$1"
tdir="$2"
shift 2

find "$tdir" -name '*.in' -print | \
    {
        i=0
        while read infile
        do
            cat "$infile" \
                | ./$exe 2>/dev/null \
                | diff - "$(echo "$infile" | sed 's/in$/out/')" "$@" \
                || { echo "Test #$i ($infile) failed" >&2; exit 1; }
            i=$(expr $i + 1)
        done
        echo "All $i tests passed"
    }
